### ISSUE TITLE
Why it show desc message when run rspec?

### ISSUE THREAD

**Issue by seikyo-cho** [erikhuda/thor#499] opened 2015-09-02 09:32 UTC
In this case:

lib/tasks/my_task.rb

```ruby
    require 'thor'

    module Tasks
      class MyTask < Thor
        desc 'My Batch', 'This is my awesome batch'
        option :date
        def execute(type)
          # do_something
        end
      end
    end

    Tasks::MyTask.start(ARGV)
```

spec/lib/tasks/my_task_spec.rb

```ruby
    # do_some_test
```

When run `bundle exec rspec`, the message been:

```bash
Run options: exclude {:heavy=>true}
    .......................................................................................................................................................................
    ........................................................************.......................................................................................................................................................................................................******
Commands:
      rspec help [COMMAND]  # Describe available commands or one specific command
      rspec My Batch          # This is my awesome batch
.................................................................................................................................................................................................................................................................................
```

Why the desc messages been shown here? How to config to remove them?

**Comment by maxmeyer** [comment] 2015-09-02 11:46
What are you testing in `spec/lib/tasks/my_task_spec.rb`? Do you use [`aruba`](https://github.com/cucumber/aruba) for testing? Do you `require` that file anywhere?

BTW: You can leave out `ARGV`.

**Comment by seikyo-cho** [comment] 2015-09-03 01:02
My test like:

```ruby
require 'spec_helper'

describe 'Test my task' do
  context 'With date option' do
    before do
      @option = { date: '20150903' }
    end
    
    it 'Can insert to db' do
      expect do
        Tasks::MyTask.new.invoke(:execute, ['commit'], @option)
      end.to change(ProductTable, :count).by(1)
    end
  end
end
```

I didn't use aruba.

**Comment by seikyo-cho** [comment] 2015-09-03 01:55
I think I have known how to deal with it. After I removed this line:

```ruby
Tasks::MyTask.start(ARGV)
```

and run `bundle exec rspec` again, the message disappeared.

But what's meaning about `Tasks::MyTask.start(ARGV)`? I found it in the official document. It looks like it is unnecessary.

**Comment by maxmeyer** [comment] 2015-09-03 06:32
> But what's meaning about Tasks::MyTask.start(ARGV)? I found it in the official document. It looks like it is unnecessary.

Of course, you need it. It think the problem is: It's part of the file you defined the task in. I also assume that you `require "tasks/mytask"` somewhere in your `spec_helper.rb`. `.start` runs your task and parses `ARGV` when it's called. Nothing you want to happen in your test suite.

Just decide what your API should be:
* Something which should be used from within ruby code only. Then use the `#invoke`-method
* Something which is started via cli use the `.start`-method

If possible try to move `Tasks::MyTask.start(ARGV)` to `bin/mytask` or something which suits your needs better.

~~~ruby
#!/usr/bin/env ruby

# Make sure your lib is found by `require`
$LOAD_PATH << File.expand_path('../../', __FILE__)

# require your task to make it available within this file
require 'tasks/mytask'

# start your task
Tasks::MyTask.start
~~~

Although I'm biased - I'm one of `aruba`'s maintainers, you may want to give it a try your API is a cli-one. You can use the [README](https://github.com/cucumber/aruba/blob/master/README.md) and [this](https://github.com/cucumber/aruba/blob/master/features/getting_started/supported_testing_frameworks.feature) or all other features found in the directory as starting point. If you prefer to learn by example, have a look [here](https://github.com/rspec/rspec-core/tree/master/features) or even [here](https://github.com/fedux-org/middleman-presentation/tree/master/middleman-presentation-core/features)

**Comment by seikyo-cho** [comment] 2015-09-03 08:13
@maxmeyer 
Thank you again for your so good reply.
In deed, I created that task file in my rails project and want to use it only. For example, I want to run that task by hand when I want to use it any time. So I should write this line under that file:
```ruby
Tasks::MyTask.start(ARGV)
```
You say I should write it to `bin/mytask`, then how to use it?
I want to use it by `rails runner`:
```bash
RAILS_ENV=production bin/rails runner Tasks::MyTask execute commit --date '20150903'
```
---
I will use `aruba` from now on:-)

**Comment by maxmeyer** [comment] 2015-09-03 08:40
> You say I should write it to bin/mytask, then how to use it? I want to use it by rails runner:

No, then there's no need to have that file. I think, you do not need to use the `.start`-line if you are going  to use it in your rails runner.

Given that you created a rubygem `yourgem` which includes

~~~
bin/yourgem-cli
~~~

In that file, you can add the `.start`-line. For examples look [here](https://github.com/fedux-org/middleman-presentation/blob/master/middleman-presentation/bin/middleman-presentation) (bin/middleman-presentation) and [here](https://github.com/fedux-org/middleman-presentation/blob/master/middleman-presentation-core/lib/middleman-presentation-core/cli/runner.rb) (the "Thor"-Class).


If you installed it, you can then run it from commandline - bash, zsh (Linux, Mac OS X) or even cmd.exe (Windows)

~~~bash
$ gem install yourgem
$ yourgem-cli execute
~~~

If everything works for, you might want to share that via documentation added to `Thor` or just publish a blog post. Just ask @sferik if he would accept such a PR - I'm just a user of tor myself.

**Comment by maxmeyer** [comment] 2015-09-03 08:40
@sferik I think you can close this one, it's not an issue of thor.

**Closed** 2015-09-03 09:56 UTC

**Comment by seikyo-cho** [comment] 2015-09-03 09:59
@maxmeyer 
Thank you. You are right. I moved that task to `bin/rails`:
```ruby
require 'tasks/my_task'
Tasks::MyTask.start(ARGV)
```
All work fine.
